<a href="https://colab.research.google.com/github/nandiniranjansinha/sephora-beauty-analytics/blob/main/Sephora.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
product_df = pd.read_csv("/content/product_info.csv")

In [ ]:
product_df.head(5)

,product_id,product_name,brand_id,brand_name,loves_count,rating,reviews,size,variation_type,variation_value,...,online_only,out_of_stock,sephora_exclusive,highlights,primary_category,secondary_category,tertiary_category,child_count,child_max_price,child_min_price
0,P473671,Fragrance Discovery Set,6342,19-69,6320,3.6364,11.0,NaN,NaN,NaN,...,1,0,0,"['Unisex/ Genderless Scent', 'Warm &Spicy Scen...",Fragrance,Value & Gift Sets,Perfume Gift Sets,0,NaN,NaN
1,P473668,La Habana Eau de Parfum,6342,19-69,3827,4.1538,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,85.0,30.0
2,P473662,Rainbow Bar Eau de Parfum,6342,19-69,3253,4.2500,16.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
3,P473660,Kasbah Eau de Parfum,6342,19-69,3018,4.4762,21.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
4,P473658,Purple Haze Eau de Parfum,6342,19-69,2691,3.2308,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0

In [ ]:
print(product_df.columns)
print(product_df.shape)
print(product_df.size)

Index(['product_id', 'product_name', 'brand_id', 'brand_name', 'loves_count',
       'rating', 'reviews', 'size', 'variation_type', 'variation_value',
       'variation_desc', 'ingredients', 'price_usd', 'value_price_usd',
       'sale_price_usd', 'limited_edition', 'new', 'online_only',
       'out_of_stock', 'sephora_exclusive', 'highlights', 'primary_category',
       'secondary_category', 'tertiary_category', 'child_count',
       'child_max_price', 'child_min_price'],
      dtype='object')
(8494, 27)
229338

In [ ]:
product_df.drop(['brand_id', 'size', 'variation_type', 'variation_value', 'variation_desc', 'ingredients', 'value_price_usd', 'sale_price_usd', 'highlights', 'child_count', 'child_max_price', 'child_min_price'], axis = 1, inplace = True)

In [ ]:
print(product_df.shape)

(8494, 15)

In [ ]:
product_df.isnull().sum()

product_id              0
product_name            0
brand_name              0
loves_count             0
rating                278
reviews               278
price_usd               0
limited_edition         0
new                     0
online_only             0
out_of_stock            0
sephora_exclusive       0
primary_category        0
secondary_category      8
tertiary_category     990
dtype: int64

In [ ]:
product_df.dropna(subset = ['rating','reviews'], inplace = True)
product_df['secondary_category'].fillna('Unknown', inplace = True)

/tmp/ipykernel_9481/2323523493.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  product_df['secondary_category'].fillna('Unknown', inplace = True)

In [ ]:
product_df.isnull().sum()

product_id              0
product_name            0
brand_name              0
loves_count             0
rating                  0
reviews                 0
price_usd               0
limited_edition         0
new                     0
online_only             0
out_of_stock            0
sephora_exclusive       0
primary_category        0
secondary_category      0
tertiary_category     911
dtype: int64

In [ ]:
product_df.shape

(8216, 15)

In [ ]:
review_0_df = pd.read_csv('/content/reviews_0-250.csv')
review_1_df = pd.read_csv('/content/reviews_1250-end.csv')
review_2_df = pd.read_csv('/content/reviews_250-500.csv')
review_3_df = pd.read_csv('/content/reviews_500-750.csv')
review_4_df = pd.read_csv('/content/reviews_750-1250.csv')

reviews_df = pd.concat([review_0_df,review_1_df,review_2_df,review_3_df,review_4_df])

/tmp/ipykernel_9481/116479119.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  review_0_df = pd.read_csv('/content/reviews_0-250.csv')
/tmp/ipykernel_9481/116479119.py:2: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  review_1_df = pd.read_csv('/content/reviews_1250-end.csv')
/tmp/ipykernel_9481/116479119.py:5: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  review_4_df = pd.read_csv('/content/reviews_750-1250.csv')

In [ ]:
reviews_df.shape

(1094411, 19)

In [ ]:
reviews_df.columns

Index(['Unnamed: 0', 'author_id', 'rating', 'is_recommended', 'helpfulness',
       'total_feedback_count', 'total_neg_feedback_count',
       'total_pos_feedback_count', 'submission_time', 'review_text',
       'review_title', 'skin_tone', 'eye_color', 'skin_type', 'hair_color',
       'product_id', 'product_name', 'brand_name', 'price_usd'],
      dtype='object')

In [ ]:
reviews_df = reviews_df.drop(["Unnamed: 0", "author_id", "total_neg_feedback_count", "total_pos_feedback_count", "review_text", "eye_color", "hair_color", "product_name", "brand_name", "price_usd"], axis = 1)

In [ ]:
reviews_df.columns

Index(['rating', 'is_recommended', 'helpfulness', 'total_feedback_count',
       'submission_time', 'review_title', 'skin_tone', 'skin_type',
       'product_id'],
      dtype='object')

In [ ]:
reviews_df.isnull().sum()

rating                       0
is_recommended          167988
helpfulness             561592
total_feedback_count         0
submission_time              0
review_title            310654
skin_tone               170539
skin_type               111557
product_id                   0
dtype: int64

In [ ]:
reviews_df = reviews_df.drop(['helpfulness'], axis = 1)
reviews_df['skin_type'] = reviews_df['skin_type'].fillna('Unknown')

In [ ]:
reviews_df.shape

(1094411, 8)

In [ ]:
reviews_df.isnull().sum()

rating                       0
is_recommended          167988
total_feedback_count         0
submission_time              0
review_title            310654
skin_tone               170539
skin_type                    0
product_id                   0
dtype: int64

In [ ]:
reviews_df['submission_time'] = pd.to_datetime(reviews_df['submission_time'])
reviews_df['submission_time'].dtype

dtype('<M8[ns]')

In [ ]:
reviews_df['submission_time']

0        2023-02-01
1        2023-03-21
2        2023-03-21
3        2023-03-20
4        2023-03-20
            ...
119312   2022-04-29
119313   2022-04-29
119314   2022-04-29
119315   2022-04-29
119316   2022-04-29
Name: submission_time, Length: 1094411, dtype: datetime64[ns]

In [ ]:
product_df.to_csv('clean_products.csv', index = False)
reviews_df.to_csv('clean_reviews.csv', index = False)